/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuan2_luongnhapxuat;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author win 10
 */
public class Bai1Form extends javax.swing.JFrame {

    /**
     * Creates new form Bai1Form
     */
    public Bai1Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtShow = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnReadBinary = new javax.swing.JButton();
        btnReadText = new javax.swing.JButton();
        btnWriteBinary = new javax.swing.JButton();
        btnWriteText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tệp tin:");

        jLabel2.setText("Nhập chuỗi:");

        txtShow.setEnabled(false);

        jLabel3.setText("Nhập nội dung file:");

        btnReadBinary.setText("Đọc file nhị phân");
        btnReadBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadBinaryActionPerformed(evt);
            }
        });

        btnReadText.setText("Đọc file văn bản");
        btnReadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadTextActionPerformed(evt);
            }
        });

        btnWriteBinary.setText("Ghi file nhị phân");
        btnWriteBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteBinaryActionPerformed(evt);
            }
        });

        btnWriteText.setText("Ghi file văn bản");
        btnWriteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtShow, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReadText)
                                .addGap(96, 96, 96)
                                .addComponent(btnWriteText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReadBinary)
                                .addGap(90, 90, 90)
                                .addComponent(btnWriteBinary)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadBinary)
                    .addComponent(btnWriteBinary))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWriteText)
                    .addComponent(btnReadText))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadBinaryActionPerformed
        // TODO add your handling code here:
        byte a[];
        File file;
        try {
            file = new File(txtPath.getText());
            FileInputStream fi = new FileInputStream(file);
            a = new byte[fi.available()];
            fi.read(a);
            fi.close();
            txtShow.setText(new String(a));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReadBinaryActionPerformed

    private void btnReadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadTextActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fr = new FileReader(new File(txtPath.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];
            while (fr.ready()) {
                int len = fr.read(ca);
                sb.append(ca,0,len);
            }
            fr.close();
            txtShow.setText(sb+"");
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btnReadTextActionPerformed

    private void btnWriteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteTextActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter fw = new FileWriter(new File(txtPath.getText()));
            fw.write(txtValue.getText());
            fw.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnWriteTextActionPerformed

    private void btnWriteBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteBinaryActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
        int i;
        char s[] = txtValue.getText().toCharArray();
        for ( i = 0; i < s.length; i++) {
            a[i] = (byte) s[i];
        }
        try {
            file = new File(txtPath.getText());
            FileOutputStream fo = new FileOutputStream(file);
            fo.write(a);
            fo.close();
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnWriteBinaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai1Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadBinary;
    private javax.swing.JButton btnReadText;
    private javax.swing.JButton btnWriteBinary;
    private javax.swing.JButton btnWriteText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtShow;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
